# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15833cdeceb979911ea56f301366f803356a1a15a3a1f117899aa6467301d357023d86cf394cdc49d745da1f9e891fccc2a02e43936908615c696f712ad0a685

test:
  secret_key_base: 944636a1a2a0074f9a10b2fe4aada904c1d3a04bca1899813b8cc714f4710c934c0eb106157283d454699d35ad01ac617248397fc3d613005852695661c09ab4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
